### ISSUE TITLE
SPLIT_TOKEN for TCA-Override Files ignored

### ISSUE THREAD

**Issue by Besek** [FriendsOfTYPO3/extension_builder#257]
Hi dear Extension-Builder Devs

I am using the 9.5 Version of the Extension-Builder (hash 8f88812, Update Settings.cfg in docs).

In the settings.yaml File i set the Overrides-Folder to keep or merge (both the same result) and add the SPLIT_TOKEN to the bottom of the file (## EXTENSION BUILDER DEFAULTS END TOKEN - Everything BEFORE this line is overwritten with the defaults of the extension builder).

When i now save the extension in the extension-builder, the TCA-File will be overriden even with the changes i mentioned further above. However, it does work for other files like ext_tables.sql

Excerpt from settings.yaml:
---

```
overwriteSettings:
  Classes:
    Controller: keep
    Domain:
      Model: merge
      Repository: keep

  Configuration:
    Overrides: keep
    #TCA merge not possible - use overrides directory
    FlexForms: keep
    TypoScript: merge
```

---
[ExtensionBuilder.txt](https://github.com/FriendsOfTYPO3/extension_builder/files/4117463/ExtensionBuilder.txt)
