### ISSUE TITLE
set 'keep' for Configuration/Extbase/Persistence/Classes.php didn't get respected

### ISSUE THREAD

**Issue by X-Tender** [FriendsOfTYPO3/extension_builder#354]
**Describe the bug**
I've configured that the ExtBuilder didnt overrwrite my Classes.php but he still do.
```yaml
overwriteSettings:
  Configuration:
    #TCA merge not possible - use overrides directory
    TypoScript: merge
    Extbase:
      Persistence:
        Classes.php: keep
```
**To Reproduce**
1. Set overwriteSettings
2. Create file Configuration/Extbase/Persistence/Classes.php
3. Create an Entity which use \TYPO3\CMS\Extbase\Domain\Model\FrontendUser as Extended Model
4. Generate and see that it gets overridden

**Expected behavior**
Classes.php should not be changed

**TYPO3 Version**
10.4.12

**Extension Builder Version:**
Git-branch v10 compatibility

**Additional context**
